name: backend-CD

on:
  push:
    branches: [ main ]

env:
  S3_BUCKET_NAME: dgu-timetable-bucket
  PROJECT_NAME: dgu-timetable

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./2023-2-OSSProj-TurtleNeck-9/backend

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ./2023-2-OSSProj-TurtleNeck-9/backend

      - name: Make zip file
        run: zip -r ${GITHUB_SHA}.zip .
        working-directory: ./2023-2-OSSProj-TurtleNeck-9/backend
        # Ensure the zip file contains only necessary files for deployment

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_S3_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_S3_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Copy script files
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy
        working-directory: ./2023-2-OSSProj-TurtleNeck-9/backend
        # Ensure the 'scripts' directory exists at this location

      # Upload to S3
      - name: Upload to S3
        run: aws s3 cp ./${GITHUB_SHA}.zip s3://${S3_BUCKET_NAME}/${PROJECT_NAME}/${GITHUB_SHA}.zip
        working-directory: ./2023-2-OSSProj-TurtleNeck-9/backend
        # Ensure the 'deploy' directory
