name: backend-CD

on:
  push:
    branches:
      - main
      - feature/*

env:
  S3_BUCKET_NAME: dgu-timetable-bucket
  PROJECT_NAME: dgu-timetable

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: current directory check
        run: ls -a

      - name: Grant execute permission for gradlew
        working-directory: backend
        run: chmod +x ./gradlew

      - name: Convert line endings of gradlew
        working-directory: backend
        run: sed -i 's/\r$//' ./gradlew

      - name: Build with Gradle
        working-directory: backend
        run: ./gradlew build

      - name: Make zip file
        run: zip -r dgu-timetable.zip .
        # Ensure the zip file contains only necessary files for deployment

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_S3_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_S3_SECRET }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Copy script files
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy
        # Ensure the 'scripts' directory exists at this location

      # Upload to S3
      - name: Upload to S3
        run: aws s3 cp ./dgu-timetable.zip s3://${S3_BUCKET_NAME}/${PROJECT_NAME}/${dgu-timetable.zip
        # Ensure the 'deploy' directory
