name: backend CI

on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches: [ main ]  # main branch로 pull request될 때 실행됩니다.

jobs:
  build-and-test-backend:
    name: Backend CI
    runs-on: ubuntu-latest # GitHub의 기본 실행 환경을 사용합니다.

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
